version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: criti-pixel
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
  
  app:
    build:
      context: .
    depends_on:
      - mysql
    entrypoint: |
      sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done; php bin/console cache:clear"
