name: Continuous integration

on: 
  push:
    branches:
      - main  # Ajoute une branche cible, par exemple, main.

jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Mise à jour vers la version 3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          tools: castor

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV  # Utilisation de fichiers d'environnement

      - name: Cache composer dependencies
        uses: actions/cache@v3  # Mise à jour vers la version 3
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Build
        run: |
          composer install
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
          php bin/console sass:build

      - name: Tests
        run: php bin/phpunit

      - name: Analysis
        run: vendor/bin/phpstan analyse src --level=max  # Ajout de l'analyse statique avec PHPStan
