name: Continuous integration
on: [push]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean up APT
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-broken
          sudo apt-get autoremove -y
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          tools: castor
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build
        run: |
          docker-compose -f "docker-compose.yml" up -d --build
          sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done"
          composer install
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
          php bin/console sass:build
      - name: Tests
        run: php bin/phpunit
      - name: Analysis
        run: php vendor/bin/phpstan
